# Generated by Django 5.0.7 on 2024-08-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="estimated_time",
            field=models.DurationField(verbose_name="Время начала выполнения"),
        ),
    ]
