# Generated by Django 5.0.7 on 2024-08-12 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_estimated_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="start_at",
            field=models.TimeField(
                default=datetime.datetime(2024, 8, 12, 22, 57, 38, 43774),
                verbose_name="Время начала выполнения",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="habit",
            name="estimated_time",
            field=models.DurationField(verbose_name="Время на выполнение"),
        ),
    ]
