# Generated by Django 5.0.7 on 2024-08-12 20:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_habit_start_at_alter_habit_estimated_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="start_date",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата начала",
            ),
            preserve_default=False,
        ),
    ]
