# Generated by Django 5.0.7 on 2024-08-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_habit_start_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="start_date",
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("daily", "daily"),
                    ("monday", "monday"),
                    ("tuesday", "tuesday"),
                    ("wednesday", "wednesday"),
                    ("thursday", "thursday"),
                    ("friday", "friday"),
                    ("saturday", "saturday"),
                    ("sunday", "sunday"),
                ],
                default="daily",
                max_length=9,
                verbose_name="периодичность",
            ),
        ),
    ]
