# Generated by Django 5.0.7 on 2024-08-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_remove_habit_start_date_alter_habit_periodicity"),
    ]

    operations = [
        migrations.CreateModel(
            name="HabitPeriodicity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("MON", "Понедельник"),
                            ("TUE", "Вторник"),
                            ("WED", "Среда"),
                            ("THU", "Четверг"),
                            ("FRI", "Пятница"),
                            ("SAT", "Суббота"),
                            ("SUN", "Воскресенье"),
                        ],
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="habit",
            name="periodicity",
        ),
        migrations.AddField(
            model_name="habit",
            name="periodicity",
            field=models.ManyToManyField(
                to="habits.habitperiodicity", verbose_name="периодичность"
            ),
        ),
    ]
