# Generated by Django 5.0.7 on 2024-08-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0008_habitperiodicity_period_alter_habitperiodicity_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="estimated_time",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Время на выполнение"
            ),
        ),
    ]
