# Generated by Django 5.0.7 on 2024-08-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0009_alter_habit_estimated_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.ManyToManyField(
                max_length=50,
                to="habits.habitperiodicity",
                verbose_name="периодичность",
            ),
        ),
    ]
